spring:
  profiles: local
server:
  port: 10500
  tomcat:
    basedir: /data/deployer/redis-api/tomcat
log:
  path: ./logs
  level: INFO
jedis:
  host: 127.0.0.1
  port: 6379
  password: 
  timeout: 1000
  pool:
      maxTotal: 100
      maxIdle: 10
      maxWaitMillis: 100000